"use client";

import Top from "@/components/Top";
import "../styles/globals.scss";
import { Inter, Source_Sans_Pro } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Top />
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
